services:
  - type: web
    name: saros-anonymisation
    runtime: docker
    envVars:
      - key: SAROS_ANON_FILE_STORAGE_PATH
        value: /tmp/saros-files
      - key: SAROS_ANON_ANTHROPIC_API_KEY
        sync: false
      - key: SAROS_ANON_OPENAI_API_KEY
        sync: false
