services:
  - type: web
    name: saros-anonymisation
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn modules.anonymisation.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SAROS_ANON_FILE_STORAGE_PATH
        value: /tmp/saros-files
      - key: SAROS_ANON_ANTHROPIC_API_KEY
        sync: false
      - key: SAROS_ANON_OPENAI_API_KEY
        sync: false
